### ISSUE TITLE
Fix that link checker

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/static-analysis#492]
Our little link checker is a teensy bit annoying. Working on [lychee](https://github.com/hello-rust/lychee), which will have automatic retry and backoff functionality as well as Github token support. This is a tracking issue for replacing the current link checker with lychee.

## Todo

* [ ] Finish retry and backoff in lychee
* [x] Wrap lychee into a Github action
* [x] Publish action on Marketplace
* [x] Replace current link checker with this new action

**Comment by mre** [comment]
Deactivated that link checker for now because it was getting ridiculous. 😆
We should move to lychee when time allows.

**Comment by mre** [comment]
Adding a comment here to avoid this issue getting closed. I still would be very interested to use lychee.
If you want to help out, please add a comment here.

**Comment by mre** [comment]
We're using lychee now. 🎉
